[workspace]
members = [
  "crates/hobble",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
license = "MIT"
repository = "https://github.com/voidzero-dev/hobble"

[workspace.dependencies]
anyhow = "1.0.100"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
