[workspace]
members = [
  "crates/*",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
license = "MIT"
repository = "https://github.com/wan9chi/hobble"

[workspace.dependencies]
anyhow = "1.0.100"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
tempfile = "3.27.0"
hobble_sandbox = { path = "crates/hobble_sandbox" }
hobble_sandbox_linux = { path = "crates/hobble_sandbox_linux" }
hobble_sandbox_macos = { path = "crates/hobble_sandbox_macos" }
hobble_sandbox_profile = { path = "crates/hobble_sandbox_profile" }
hobble_command_test = { path = "crates/hobble_command_test" }
base64 = "0.22.1"
ctor = "1.0.7"
wincode = "0.5.5"
landlock = "0.4.5"
