[package]
name = "hobble_sandbox"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
ctor = { workspace = true }
hobble_sandbox_profile = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
hobble_sandbox_linux = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
hobble_sandbox_macos = { workspace = true }

[dev-dependencies]
hobble_command_test = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
